import crypto from 'crypto';

/**
 * Standard BYOK Encryption utilities utilizing AES-256-GCM.
 * Ensures Facttic platform handles conversational payloads with zero-knowledge
 * resting state if a customer key is provided.
 */

const ALGORITHM = 'aes-256-gcm';
const IV_LENGTH = 16;
const SALT_LENGTH = 64;
const TAG_LENGTH = 16;
const KEY_LENGTH = 32;

/**
 * Encrypts arbitrary stringified data into an AES-256-GCM cipher payload using a customer's raw Base64 key.
 * The output format matches `iv:authTag:encryptedData` in base64 layout.
 * 
 * @param plaintext The string format payload to encrypt (usually JSON.stringify)
 * @param base64Key The customer's 32-byte BYOK key, base64 encoded
 * @returns Combined base64 cipher payload preserving initialization vector & auth tag
 */
export function encryptData(plaintext: string, base64Key: string): string {
  if (!base64Key) {
    throw new Error('Customer BYOK key is required for encryption.');
  }

  const keyBuffer = Buffer.from(base64Key, 'base64');
  if (keyBuffer.length !== KEY_LENGTH) {
    throw new Error(`Invalid BYOK key length. Expected ${KEY_LENGTH} bytes, got ${keyBuffer.length}`);
  }

  const iv = crypto.randomBytes(IV_LENGTH);
  const cipher = crypto.createCipheriv(ALGORITHM, keyBuffer, iv);
  
  let encrypted = cipher.update(plaintext, 'utf8', 'base64');
  encrypted += cipher.final('base64');
  
  const authTag = cipher.getAuthTag();

  return `${iv.toString('base64')}:${authTag.toString('base64')}:${encrypted}`;
}

/**
 * Decrypts a combined BYOK payload back into its plaintext format.
 * 
 * @param cipherPayload The payload generated by encryptData
 * @param base64Key The customer's 32-byte BYOK key, base64 encoded
 * @returns Plaintext string representation
 */
export function decryptData(cipherPayload: string, base64Key: string): string {
  if (!cipherPayload || !base64Key) {
    throw new Error('Both cipherPayload and customer BYOK key are required for decryption.');
  }

  const keyBuffer = Buffer.from(base64Key, 'base64');
  if (keyBuffer.length !== KEY_LENGTH) {
    throw new Error(`Invalid BYOK key length. Expected ${KEY_LENGTH} bytes, got ${keyBuffer.length}`);
  }

  const parts = cipherPayload.split(':');
  if (parts.length !== 3) {
    throw new Error('Invalid cipher payload format structure.');
  }

  const [ivStr, authTagStr, encryptedStr] = parts;
  
  const iv = Buffer.from(ivStr, 'base64');
  const authTag = Buffer.from(authTagStr, 'base64');
  
  const decipher = crypto.createDecipheriv(ALGORITHM, keyBuffer, iv, { authTagLength: 16 });
  decipher.setAuthTag(authTag);
  
  let decrypted = decipher.update(encryptedStr, 'base64', 'utf8');
  decrypted += decipher.final('utf8');

  return decrypted;
}
