import { NextResponse } from 'next/server';
import { TrustBoundary } from '@/core/externalTrust/trustBoundary';
import crypto from 'node:crypto';

/**
 * GET /api/compliance/verify-signature?token=<token>
 *
 * Public endpoint — no auth required.
 * Compliance auditors use this to verify the authenticity of a signed
 * evidence token generated by ComplianceTokenGenerator.generateToken().
 *
 * Token format: base64url(payload).base64url(signature)
 * Signing algorithm: Ed25519 (via TrustBoundary keypair)
 *
 * NOTE: TrustBoundary uses an ephemeral keypair generated at process start.
 * In production, replace with keys loaded from a vault/secret manager so
 * tokens remain verifiable across restarts.
 */
export async function GET(req: Request) {
  const { searchParams } = new URL(req.url);
  const token = searchParams.get('token');

  if (!token) {
    return NextResponse.json(
      { valid: false, error: 'Missing token parameter' },
      { status: 400 }
    );
  }

  const parts = token.split('.');
  if (parts.length !== 2) {
    return NextResponse.json(
      { valid: false, error: 'Malformed token: expected base64url(payload).base64url(signature)' },
      { status: 400 }
    );
  }

  const [b64Payload, b64Signature] = parts;

  let payload: Record<string, unknown>;
  let signatureBuffer: Buffer;

  try {
    const payloadJson = Buffer.from(b64Payload, 'base64url').toString('utf-8');
    payload = JSON.parse(payloadJson);
  } catch {
    return NextResponse.json(
      { valid: false, error: 'Malformed token: payload is not valid JSON' },
      { status: 400 }
    );
  }

  try {
    signatureBuffer = Buffer.from(b64Signature, 'base64url');
  } catch {
    return NextResponse.json(
      { valid: false, error: 'Malformed token: signature is not valid base64url' },
      { status: 400 }
    );
  }

  try {
    // Re-serialize payload exactly as it was signed (ComplianceTokenGenerator stringifies the payload object)
    const payloadForVerification = Buffer.from(JSON.stringify(payload));

    const isValid = crypto.verify(
      null,
      payloadForVerification,
      TrustBoundary.publicKey,
      signatureBuffer
    );

    if (!isValid) {
      return NextResponse.json(
        { valid: false, error: 'INVALID_SIGNATURE: Cryptographic verification failed' },
        { status: 200 }
      );
    }

    return NextResponse.json({
      valid: true,
      payload,
      verified_at: new Date().toISOString(),
      algorithm: 'Ed25519',
    });

  } catch (err: any) {
    return NextResponse.json(
      { valid: false, error: `Verification error: ${err.message}` },
      { status: 400 }
    );
  }
}
