const fs = require('fs');
const path = require('path');

const targetDirs = ['app', 'components', 'lib'];
let cleanedFiles = [];

function walk(dir, callback) {
  const list = fs.readdirSync(dir);
  list.forEach((file) => {
    file = path.join(dir, file);
    const stat = fs.statSync(file);
    if (stat && stat.isDirectory()) {
      walk(file, callback);
    } else {
      callback(file);
    }
  });
}

function processFile(file) {
  if (!file.match(/\.(tsx|ts|jsx|js|css)$/)) return;
  
  let content = fs.readFileSync(file, 'utf8');
  let original = content;

  // 1. Remove all dark:* tailwind classes
  content = content.replace(/\bdark:[^\s'"`]+/g, '');
  
  // 2. Remove zinc-* classes
  content = content.replace(/\b(bg|text|border)-zinc-\d+\b/g, '');
  content = content.replace(/\bzinc-\d+\b/g, ''); // catch any isolated ones
  
  // 3. Handle inline styles string
  content = content.replace(/style={{[^}]+}}/g, '');
  
  // 4. Handle text-white
  // Only replace text-white if it's not explicitly in a high contrast header
  // To be perfectly robust as per user: "Remove all"
  // Let's replace text-white with text-[var(--parch)] where beneficial, but in Facttic
  // bg-[var(--navy)] looks bad if text is default black. We'll leave `text-white` inside the files I just built (HealthCard, Sidebar, etc) 
  // Wait, the user specifically said "Remove all text-white". I will replace text-white with text-[var(--parch)].
  content = content.replace(/\btext-white\b/g, 'text-[var(--parch)]');
  
  if (content !== original) {
    // clean up any double spaces generated by class removal
    content = content.replace(/className=(['"`])\s+/g, 'className=$1');
    content = content.replace(/\s+(['"`])/g, '$1');
    content = content.replace(/ {2,}/g, ' ');
    
    fs.writeFileSync(file, content, 'utf8');
    cleanedFiles.push(file);
  }
}

targetDirs.forEach(dir => {
  const fullPath = path.join(__dirname, '..', dir);
  if (fs.existsSync(fullPath)) {
    walk(fullPath, processFile);
  }
});

// Special cleanup for layout.tsx (Google Fonts)
const layoutPath = path.join(__dirname, '../app/layout.tsx');
if (fs.existsSync(layoutPath)) {
  let layoutContent = fs.readFileSync(layoutPath, 'utf8');
  if (layoutContent.includes('next/font/google')) {
    layoutContent = layoutContent.replace(/import {[^}]+} from 'next\/font\/google';\n/g, '');
    layoutContent = layoutContent.replace(/const \w+ = [A-Za-z_]+\({[\s\S]*?}\);\n\n/g, '');
    layoutContent = layoutContent.replace(/ className={\`[^`]+\`}/g, '');
    fs.writeFileSync(layoutPath, layoutContent, 'utf8');
    if (!cleanedFiles.includes(layoutPath)) cleanedFiles.push(layoutPath);
  }
}

console.log("CLEANED_FILES_START");
cleanedFiles.forEach(f => console.log(f.replace(__dirname + '/../', '')));
console.log("CLEANED_FILES_END");
